#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.configuration-cache=true


kotlin.code.style=official
android.useAndroidX=true

kotlin.mpp.stability.nowarn=true

# Experimental: incremental compilation for Kotlin/Native (speeds up iOS framework rebuilds)
kotlin.incremental.native=true
